FROM node:lts-alpine

ENV PORT 3000
ENV API 134.122.69.192	
ENV BACK_URL docwoo-back-stage.scenario-projects.com
ENV FRONT_URL docwoo-front-stage.scenario-projects.com		
# Create app directory
WORKDIR /home/node/app
# Installing dependencies
COPY ["package.json", "package-lock.json", "./"]

RUN npm  install
# Copying source files
COPY . ./
# Building app
RUN npm run build

EXPOSE 3000
# Running the app
CMD npm run start