FROM node:lts-alpine

ENV PORT 3000


ENV API 161.35.23.61
ENV API_URL https://docwoo-back-dev.scenario-projects.com/

# Create app directory
WORKDIR /home/node/app
# Installing dependencies
COPY ["package.json", "package-lock.json", "./"]

RUN npm  install
# Copying source files
COPY . ./
# Building app
RUN npm run build

EXPOSE 3000
# Running the app
CMD npm run start
