version: "3.3"
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.stage
    volumes:
      - /home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next