FROM node:lts-alpine

ENV PORT=3000
ENV HOST_ENV=stage
ENV API_URL=https://docwoo-back-dev.scenario-projects.com/api/v1

# Create app directory
WORKDIR /home/node/app
# Installing dependencies
COPY ["package.json", "package-lock.json", "./"]

RUN npm  install
# Copying source files
COPY . ./
# Building app
RUN npm run build

EXPOSE 3000
# Running the app
CMD npm run start
